### ISSUE TITLE
Latex not rendering 

### ISSUE THREAD

**Issue by RubenSystems** [vatai/vatai.github.io#4]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

The latex is not rendering on the blog page

### How to reproduce the bug

Open blog page 

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Deployed site

### More info

Really enjoyed the blog posts! Latex is not rendering on them.

**Comment by vatai** [comment]
Hi! Sorry but something is wrong on your end. It works for me on linux+firefox and android+firefox.
![image](https://github.com/user-attachments/assets/742329be-b1f2-47bb-bb66-60c7e5c4b5da)

**Comment by RubenSystems** [comment]
The latest post works for me as well, however this page: [https://vatai.github.io/blog/2022/polyhedral-compilation-part-1/](url) doesn't on Firefox MacOS: 
<img width="1446" alt="Screenshot 2024-11-19 at 4 11 30 pm" src="https://github.com/user-attachments/assets/75b15d99-dee0-45a0-bbfe-31dda832c3ae">

**Comment by vatai** [comment]
Thanks for finding this! Indeed that post was messed up because of the move to the new Jekyll template! I'm merging the fix as we speak it should update in a few minutes!

If you're interested in collaborating on polyhedral compilation please reach out :)

**Comment by RubenSystems** [comment]
No problem - happy to help! 

Polyhedral compilation is super interesting, let me know if you have any projects, it would be great to work with you!

**Comment by vatai** [comment]
https://arxiv.org/abs/2410.03210

I'll try to add more to the Tadashi project page when I have time.
